spring.application.name=employee-manager
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
logging.level.sql=debug
spring.jpa.open-in-view=false
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml
logging.level.liquibase=DEBUG